/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesAiAutomationRouteImport } from './routes/services.ai-automation'
import { Route as ServicesCloudDevopsRouteImport } from './routes/services.cloud-devops'
import { Route as ServicesModernizationRouteImport } from './routes/services.modernization'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiAutomationRoute = ServicesAiAutomationRouteImport.update({
  id: '/services/ai-automation',
  path: '/services/ai-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCloudDevopsRoute = ServicesCloudDevopsRouteImport.update({
  id: '/services/cloud-devops',
  path: '/services/cloud-devops',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesModernizationRoute = ServicesModernizationRouteImport.update({
  id: '/services/modernization',
  path: '/services/modernization',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/modernization': typeof ServicesModernizationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/modernization': typeof ServicesModernizationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/services/ai-automation': typeof ServicesAiAutomationRoute
  '/services/cloud-devops': typeof ServicesCloudDevopsRoute
  '/services/modernization': typeof ServicesModernizationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services/ai-automation'
    | '/services/cloud-devops'
    | '/services/modernization'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services/ai-automation'
    | '/services/cloud-devops'
    | '/services/modernization'
  id:
    | '__root__'
    | '/'
    | '/services/ai-automation'
    | '/services/cloud-devops'
    | '/services/modernization'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServicesAiAutomationRoute: typeof ServicesAiAutomationRoute
  ServicesCloudDevopsRoute: typeof ServicesCloudDevopsRoute
  ServicesModernizationRoute: typeof ServicesModernizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-automation': {
      id: '/services/ai-automation'
      path: '/services/ai-automation'
      fullPath: '/services/ai-automation'
      preLoaderRoute: typeof ServicesAiAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/cloud-devops': {
      id: '/services/cloud-devops'
      path: '/services/cloud-devops'
      fullPath: '/services/cloud-devops'
      preLoaderRoute: typeof ServicesCloudDevopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/modernization': {
      id: '/services/modernization'
      path: '/services/modernization'
      fullPath: '/services/modernization'
      preLoaderRoute: typeof ServicesModernizationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServicesAiAutomationRoute: ServicesAiAutomationRoute,
  ServicesCloudDevopsRoute: ServicesCloudDevopsRoute,
  ServicesModernizationRoute: ServicesModernizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
